version: 0.2
phases:
  install:
    commands:
      - echo Installing Maven...
      - yum install -y maven
  pre_build:
    commands:
      - echo Cleaning project...
      - mvn clean
  build:
    commands:
      - echo Building the project...
      - mvn package
  post_build:
    commands:
      - echo Build completed. Preparing for deployment...
      - cp target/*.jar application.jar
artifacts:
  files:
    - Procfile
    - application.jar
    - '**/*'
